global:
  imageTag: 72a1772a7a78
keyvault:
  enabled: true
  name: "kv-jobbridge"
  tenantId: "79dabbf3-8591-44a1-b318-202d64488915"
  identityClientId: "c041558d-ddad-4e06-b819-1ff049af1d1d"
services:
  auth:
    image:
      repository: "acrjobbridge.azurecr.io/jobbridge-auth"
      tag: "72a1772a7a78"
  gateway:
    image:
      repository: "acrjobbridge.azurecr.io/jobbridge-gateway"
      tag: "72a1772a7a78"
  jobs:
    image:
      repository: "acrjobbridge.azurecr.io/jobbridge-jobs"
      tag: "72a1772a7a78"
  ai:
    image:
      repository: "acrjobbridge.azurecr.io/jobbridge-ai"
      tag: "72a1772a7a78"
  frontend:
    image:
      repository: "acrjobbridge.azurecr.io/jobbridge-frontend"
      tag: "6a997c689589"
