apiVersion: v1
kind: Pod
metadata:
  name: k6-test
  namespace: jobbridge
spec:
  containers:
  - name: k6
    image: grafana/k6
    args: ["run", "/script/k6-script.js"]
    volumeMounts:
    - name: script-volume
      mountPath: "/script"
  volumes:
  - name: script-volume
    configMap:
      name: k6-test-script
  restartPolicy: Never
