sonar.projectKey=Huste6_datn-jobBridgeSmart
sonar.organization=huste6
sonar.projectName=datn-jobBridgeSmart

sonar.sources=frontend/src,backend/cmd,backend/internal,deploy/terraforms
sonar.tests=frontend/tests,backend/tests
sonar.test.inclusions=frontend/tests/**/*.test.ts,backend/tests/**/*.go

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.go.coverage.reportPaths=backend/coverage.out

sonar.terraform.provider.azure.version=3.117.1
sonar.exclusions=**/node_modules/**,frontend/dist/**,backend/bin/**,**/.terraform/**
