apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jobbridge.fullname" . }}-secret
  labels:
    {{- include "jobbridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  CLOUDINARY_URL: {{ .Values.secrets.CLOUDINARY_URL | quote }}
  CLOUDINARY_FOLDER: {{ .Values.secrets.CLOUDINARY_FOLDER | quote }}