{{- if .Values.keyvault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "jobbridge.fullname" . }}-kv
  labels:
    {{- include "jobbridge.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyvault.identityClientId | quote }}
    keyvaultName: {{ .Values.keyvault.name | quote }}
    cloudName: ""
    objects:  |
      array:
        {{- range .Values.keyvault.secrets }}
        - |
          objectName: {{ .name }}
          objectAlias: {{ .alias }}
          objectType: secret
        {{- end }}
    tenantId: {{ .Values.keyvault.tenantId | quote }}
  secretObjects:
    - secretName: {{ include "jobbridge.fullname" . }}-secret
      type: Opaque
      data:
        {{- range .Values.keyvault.secrets }}
        - objectName: {{ .name }}
          key: {{ .alias }}
        {{- end }}
{{- end }}
