{{- if not .Values.keyvault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jobbridge.fullname" . }}-secret
  labels:
    {{- include "jobbridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.keyvault.secrets }}
  {{ .alias }}: {{ index $.Values.secretsFallback .alias | default "" | quote }}
  {{- end }}
{{- end }}